### ISSUE TITLE
dev/snapshot versions are tracked

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pdsen-corral#1]
A dev/snapshot version of the PDS build will be provided.

This will tack back to all the latest snapshot/dev versions provided in the repositories.

**Comment by jordanpadams** [comment]
this has been done for a while. see https://github.com/NASA-PDS/validate/blob/master/.github/workflows/unstable-cicd.yaml and https://github.com/NASA-PDS/validate/releases
