### ISSUE TITLE
Github Action and Documentation Generation Best Practices

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pdsen-corral#16]
Design and implement consistent Github Action and Documentation Generation Best Practices

Review those 2 actions:
https://github.com/NASA-PDS/pds-doi-service/tree/master/.github/workflows

The objective is to make them more concise so to be able to replicate easily them in the different repositories we want to connect to pdsen-corral

Per meeting on 7/30, see [SW Docs best practices](https://github.com/NASA-PDS/nasa-pds.github.io/blob/master/developer/pds_sw_docs.md) and [CI/CD Best practices](https://github.com/NASA-PDS/nasa-pds.github.io/blob/master/developer/pds_ci_cd.md).

Feel free to update the best practices docs as well.

**Comment by tloubrieu-jpl** [comment]
Sean creates github action with multiple interfaces.

Sean can share intermediate version of the new actions so that Jordan and Thomas can try them and provide feedback.

**Comment by tloubrieu-jpl** [comment]
First action created on https://github.com/NASA-PDS/git-ping

Need to think and discuss how to go forward with that. Meeting next monday ?

**Comment by tloubrieu-jpl** [comment]
We decided to develop one action to implement the workflow. Sean will do the implementation.

**Comment by jordanpadams** [comment]
ℹ️ Status: Working on overall architecture for the steps.

**Comment by jordanpadams** [comment]
@nutjob4life status: no progress since last meeting.

**Comment by tloubrieu-jpl** [comment]
15-20% done.

Should be completed around 09/15 so to be used for the next I&T. 

Most important repositories to be available are: pds-doi-service and registry which have major updates for the current build.

**Comment by tloubrieu-jpl** [comment]
Implementation done for python, but documentation or package publication not done.

Will organize a meeting with @jordanpadams @tloubrieu-jpl and @nutjob4life around this Friday 09/18

**Comment by tloubrieu-jpl** [comment]
95% done

**Comment by tloubrieu-jpl** [comment]
Meeting organized.

Development has to be published under nasa-pds organization github and dockerhub (nasapds).

Next step is to deploy the new action in pds-deep-archive.

**Comment by tloubrieu-jpl** [comment]
Should be completed tomorrow.

**Comment by tloubrieu-jpl** [comment]
The action for python is ready and tested (with pds-deep-archive, + another).

To be done later:
- use access token to upload to pypi.
- add maven support

**Comment by jordanpadams** [comment]
October Schedule Status ⏳:  On track

**Comment by jordanpadams** [comment]
📆 November Status: delayed due to increasing scope as the task was iterated over. on track for december delivery.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @nutjob4life I think the current python versioning issue and the newly created issues on roundup-action are all related to some rethinking of how we should handle releases with github actions.

I think there are a few questions / issues we need to address to make sure the actual stable release is stable :-) .

1. when / how do we trigger the github action?
    a. **Current state:** triggered by a git tag. this means that **version update** and **git tag** are manual steps that need to be performed on the repo.
    b. **Proposed improvement:** triggered by some other "pre-release" step, e.g. `release` branch or version branch (e.g. `v0.0.0` or some specific commit message to trigger. github action handles versioning, tagging, etc. we would need this trigger to somehow contain the updated version so the software knows what to increment the version to (major, minor, patch)

2. missing Github releases (NASA-PDS/roundup-action#25)
    a. **Current state:** roundup only pushes releases for unstable, but skips that step for stable.
    b. **Proposed improvement:** after tagging, github release should be created

3. missing site to github pages (NASA-PDS/roundup-action#28)
    a. **Current state:** roundup packages up the documentation and pushes to the release (although this doesn't work right now since a release is not created for stable releases)
    b. **Proposed improvement:** roundup packages up the docs, but also needs to push those docs to github pages branch (note update for maven project to use `site:stage` goal to group all docs together)

4. bug updating version after tag was created (NASA-PDS/roundup-action#26)
    a. *Current state:** roundup (or pds-github-util) increments version after the software has already been tagged, but that version should be updated prior to tagging
    b. **Proposed improvement:** use the version in the tagged release as-is

thoughts?

**Comment by jordanpadams** [comment]
📆 December Status: Delayed due to increased scope and personnel stuck on other project deliverables. no impact to build expected.
