### ISSUE TITLE
Release candidate management

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pdsen-corral#17]
Currently I&T applies with stable release of tools (e.g. 1.24.0). A side effect of it is that the documentation for this version will be published although it is not validated yet.

To avoid the publication of un-checked documentation, we want to introduce a release candidate version management.

**Comment by jordanpadams** [comment]
we have decided to proceed with tagging repos with operational versions when we deliver to I&T, and, instead, include a "BETA" when describing the RDD and Software Summaries linking to those versions.
