### ISSUE TITLE
Re-evaluate generating requirements for -dev versions

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pdsen-corral#24]
**Is your feature request related to a problem? Please describe.**
Current pdsen-corral generates REQUIREMENTS.md for each dev version, e.g. https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/requirements/0.0.8-dev/REQUIREMENTS.md . But this doesn't seem to make sense? Should we really just generate the REQUIREMENTS.md for release versions? Or if we do for development, shouldn't we remove them at release time or just use a generic `development/REQUIREMENTS.md`?

**Comment by jordanpadams** [comment]
@nutjob4life @tloubrieu-jpl not sure if this still applies after the round-up action, but just wanted to make sure we discussed and addressed this

**Comment by tloubrieu-jpl** [comment]
Remove the older dev/snapshot requirements
