### ISSUE TITLE
Kick off the activity 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pdsen-corral#27]
Initiate the AWS deployment activity.

Identify type of PDS targeted components for deployment and identify hosting service candidates (EKS, lambda, ...)

Jordan:
I would like a generic design for what it looks like for PDS services to be in the cloud
 and since we are focused on the registry right now, maybe we split these services between elastic services, versus standalone services (e.g. DOI Service, Tracking Service) versus websites maybe we do that incrementally, but that is what i am looking for if that makes sense?

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl organizes meeting with @jordanpadams @nutjob4life

**Comment by tloubrieu-jpl** [comment]
We need to figure out how to get Scott and Sean a AWS login

**Comment by jordanpadams** [comment]
@tloubrieu-jpl we should probably setup a meeting with the SAs to talk about this. they can maybe help with out plans and strategy as well.

**Comment by tloubrieu-jpl** [comment]
This ticket is on setting deployments guidelines for AWS. We could think of 2 main routes: multi-node, single node.

- Single node would be based on serverless service embedded in docker.
- Multi-node could be on kubernetes (EKS on AWS).

As for now, we want to think of AWS deployment as pilots which deployment could be used as recipes for other deployments.
